// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService 提供剪贴板功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetText 获取剪贴板文本
 */
export function GetText(): $CancellablePromise<string> {
    return $Call.ByID(1724908274);
}

/**
 * SetText 设置剪贴板文本
 */
export function SetText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(1307022678, text);
}
