// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 提供文件操作功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFolderHistory 添加文件夹到历史记录
 */
export function AddFolderHistory(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(1343484426, folderPath);
}

/**
 * ClearThumbnailCache 清除缩略图缓存目录
 */
export function ClearThumbnailCache(): $CancellablePromise<void> {
    return $Call.ByID(1825393934);
}

/**
 * GetFileDataURI 读取文件并返回 data URI
 */
export function GetFileDataURI(path: string): $CancellablePromise<string> {
    return $Call.ByID(3422778135, path);
}

/**
 * GetFiles 递归扫描文件夹，返回所有支持的照片文件
 */
export function GetFiles(folderPath: string): $CancellablePromise<$models.PhotoInfo[]> {
    return $Call.ByID(2318676780, folderPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFolderHistory 获取最近打开的文件夹列表
 */
export function GetFolderHistory(): $CancellablePromise<string[]> {
    return $Call.ByID(4086301523).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetFolderTree 获取文件夹树结构（单层子目录）
 */
export function GetFolderTree(folderPath: string): $CancellablePromise<$models.FolderNode> {
    return $Call.ByID(649709577, folderPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetThumbnail 获取照片缩略图路径（自动生成 WebP 缓存）
 */
export function GetThumbnail(path: string): $CancellablePromise<string> {
    return $Call.ByID(3646606067, path);
}

/**
 * RemoveFolderHistory 从历史记录中移除
 */
export function RemoveFolderHistory(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(758867473, folderPath);
}

/**
 * SelectFolder 打开原生文件夹选择对话框
 */
export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1349170739);
}

// Private type creation functions
const $$createType0 = $models.PhotoInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.FolderNode.createFrom;
