// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 提供文件操作功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetFileDataURI 读取文件并返回 data URI（用于前端图片预览）
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetFileDataURI(path) {
    return $Call.ByID(3422778135, path);
}

/**
 * GetFiles 递归扫描文件夹，返回所有支持的照片文件
 * @param {string} folderPath
 * @returns {$CancellablePromise<$models.PhotoInfo[]>}
 */
export function GetFiles(folderPath) {
    return $Call.ByID(2318676780, folderPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SelectFolder 打开原生文件夹选择对话框，返回选择的路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(1349170739);
}

// Private type creation functions
const $$createType0 = $models.PhotoInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
