// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PhotoInfo 照片文件信息
 */
export class PhotoInfo {
    /**
     * Creates a new PhotoInfo instance.
     * @param {Partial<PhotoInfo>} [$$source = {}] - The source object to create the PhotoInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PhotoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PhotoInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PhotoInfo(/** @type {Partial<PhotoInfo>} */($$parsedSource));
    }
}
