// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FolderNode 文件夹树节点
 */
export class FolderNode {
    "name": string;
    "path": string;
    "photoCnt": number;
    "subDirs"?: FolderNode[];

    /** Creates a new FolderNode instance. */
    constructor($$source: Partial<FolderNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("photoCnt" in $$source)) {
            this["photoCnt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderNode {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subDirs" in $$parsedSource) {
            $$parsedSource["subDirs"] = $$createField3_0($$parsedSource["subDirs"]);
        }
        return new FolderNode($$parsedSource as Partial<FolderNode>);
    }
}

/**
 * PhotoInfo 照片文件信息
 */
export class PhotoInfo {
    "path": string;
    "fileName": string;
    "ext": string;

    /** Creates a new PhotoInfo instance. */
    constructor($$source: Partial<PhotoInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("ext" in $$source)) {
            this["ext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PhotoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PhotoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PhotoInfo($$parsedSource as Partial<PhotoInfo>);
    }
}

// Private type creation functions
const $$createType0 = FolderNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
