// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PhotoInfo 照片文件信息
 */
export class PhotoInfo {
    "path": string;
    "fileName": string;
    "ext": string;

    /** Creates a new PhotoInfo instance. */
    constructor($$source: Partial<PhotoInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("ext" in $$source)) {
            this["ext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PhotoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PhotoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PhotoInfo($$parsedSource as Partial<PhotoInfo>);
    }
}
