// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 提供窗口控制功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Center 居中窗口
 */
export function Center(): $CancellablePromise<void> {
    return $Call.ByID(1770190508);
}

/**
 * Close 关闭窗口
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(594989995);
}

/**
 * Fullscreen 全屏
 */
export function Fullscreen(): $CancellablePromise<void> {
    return $Call.ByID(3290975168);
}

/**
 * GetPosition 获取窗口位置
 */
export function GetPosition(): $CancellablePromise<[number, number]> {
    return $Call.ByID(1774580860);
}

/**
 * GetSize 获取窗口大小
 */
export function GetSize(): $CancellablePromise<[number, number]> {
    return $Call.ByID(3935517014);
}

/**
 * Hide 隐藏窗口
 */
export function Hide(): $CancellablePromise<void> {
    return $Call.ByID(3880498181);
}

/**
 * IsFullscreen 检查是否全屏
 */
export function IsFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(2162673088);
}

/**
 * IsMaximised 检查是否最大化
 */
export function IsMaximised(): $CancellablePromise<boolean> {
    return $Call.ByID(1861282546);
}

/**
 * IsMinimised 检查是否最小化
 */
export function IsMinimised(): $CancellablePromise<boolean> {
    return $Call.ByID(3807610036);
}

/**
 * Maximize 最大化窗口
 */
export function Maximize(): $CancellablePromise<void> {
    return $Call.ByID(3628038887);
}

/**
 * Minimize 最小化窗口
 */
export function Minimize(): $CancellablePromise<void> {
    return $Call.ByID(2327504229);
}

/**
 * Restore 恢复窗口
 */
export function Restore(): $CancellablePromise<void> {
    return $Call.ByID(2921128009);
}

/**
 * SetAlwaysOnTop 设置窗口置顶
 */
export function SetAlwaysOnTop(alwaysOnTop: boolean): $CancellablePromise<void> {
    return $Call.ByID(1483914074, alwaysOnTop);
}

/**
 * SetMaxSize 设置最大窗口大小
 */
export function SetMaxSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(6026274, width, height);
}

/**
 * SetMinSize 设置最小窗口大小
 */
export function SetMinSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(812405396, width, height);
}

/**
 * SetPosition 设置窗口位置
 */
export function SetPosition(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3579613384, x, y);
}

/**
 * SetResizable 设置窗口是否可调整大小
 */
export function SetResizable(resizable: boolean): $CancellablePromise<void> {
    return $Call.ByID(3119186700, resizable);
}

/**
 * SetSize 设置窗口大小
 */
export function SetSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(467419402, width, height);
}

/**
 * SetTitle 设置窗口标题
 */
export function SetTitle(title: string): $CancellablePromise<void> {
    return $Call.ByID(3153857771, title);
}

/**
 * Show 显示窗口
 */
export function Show(): $CancellablePromise<void> {
    return $Call.ByID(1505614676);
}

/**
 * UnFullscreen 退出全屏
 */
export function UnFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(1605172039);
}
