// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 提供窗口控制功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Center 居中窗口
 * @returns {$CancellablePromise<void>}
 */
export function Center() {
    return $Call.ByID(1770190508);
}

/**
 * Close 关闭窗口
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(594989995);
}

/**
 * Fullscreen 全屏
 * @returns {$CancellablePromise<void>}
 */
export function Fullscreen() {
    return $Call.ByID(3290975168);
}

/**
 * GetPosition 获取窗口位置
 * @returns {$CancellablePromise<[number, number]>}
 */
export function GetPosition() {
    return $Call.ByID(1774580860);
}

/**
 * GetSize 获取窗口大小
 * @returns {$CancellablePromise<[number, number]>}
 */
export function GetSize() {
    return $Call.ByID(3935517014);
}

/**
 * Hide 隐藏窗口
 * @returns {$CancellablePromise<void>}
 */
export function Hide() {
    return $Call.ByID(3880498181);
}

/**
 * IsFullscreen 检查是否全屏
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFullscreen() {
    return $Call.ByID(2162673088);
}

/**
 * IsMaximised 检查是否最大化
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMaximised() {
    return $Call.ByID(1861282546);
}

/**
 * IsMinimised 检查是否最小化
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMinimised() {
    return $Call.ByID(3807610036);
}

/**
 * Maximize 最大化窗口
 * @returns {$CancellablePromise<void>}
 */
export function Maximize() {
    return $Call.ByID(3628038887);
}

/**
 * Minimize 最小化窗口
 * @returns {$CancellablePromise<void>}
 */
export function Minimize() {
    return $Call.ByID(2327504229);
}

/**
 * Restore 恢复窗口
 * @returns {$CancellablePromise<void>}
 */
export function Restore() {
    return $Call.ByID(2921128009);
}

/**
 * SetAlwaysOnTop 设置窗口置顶
 * @param {boolean} alwaysOnTop
 * @returns {$CancellablePromise<void>}
 */
export function SetAlwaysOnTop(alwaysOnTop) {
    return $Call.ByID(1483914074, alwaysOnTop);
}

/**
 * SetMaxSize 设置最大窗口大小
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetMaxSize(width, height) {
    return $Call.ByID(6026274, width, height);
}

/**
 * SetMinSize 设置最小窗口大小
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetMinSize(width, height) {
    return $Call.ByID(812405396, width, height);
}

/**
 * SetPosition 设置窗口位置
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<void>}
 */
export function SetPosition(x, y) {
    return $Call.ByID(3579613384, x, y);
}

/**
 * SetResizable 设置窗口是否可调整大小
 * @param {boolean} resizable
 * @returns {$CancellablePromise<void>}
 */
export function SetResizable(resizable) {
    return $Call.ByID(3119186700, resizable);
}

/**
 * SetSize 设置窗口大小
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<void>}
 */
export function SetSize(width, height) {
    return $Call.ByID(467419402, width, height);
}

/**
 * SetTitle 设置窗口标题
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function SetTitle(title) {
    return $Call.ByID(3153857771, title);
}

/**
 * Show 显示窗口
 * @returns {$CancellablePromise<void>}
 */
export function Show() {
    return $Call.ByID(1505614676);
}

/**
 * UnFullscreen 退出全屏
 * @returns {$CancellablePromise<void>}
 */
export function UnFullscreen() {
    return $Call.ByID(1605172039);
}
